"""add author_id to article

Revision ID: 0a2018476cf6
Revises: 
Create Date: 2026-03-20 22:59:27.344052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2018476cf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_article', sa.Column('author_id', sa.Integer(), nullable=False, comment='关联作者ID'))
    op.create_foreign_key(None, 'blog_article', 'blog_user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_article', type_='foreignkey')
    op.drop_column('blog_article', 'author_id')
    # ### end Alembic commands ###
